exports.getAccountList       = "SELECT * FROM ACCOUNT"
exports.createAccountList    = "CREATE TABLE ACCOUNT(USER_ID VARCHAR(50) PRIMARY KEY,"
                            + "USER_NAME VARCHAR(50) UNIQUE NOT NULL,"
                            + "PASSWORD VARCHAR(50) NOT NULL,"
                            + "EMAIL VARCHAR(355) UNIQUE NOT NULL,"
                            + "CREATED_ON TIMESTAMP NOT NULL,"
                            + "LAST_LOGIN TIMESTAMP)"
exports.addAccount     = "INSERT INTO account (user_id, user_name, password, email, created_on, last_login) VALUES ( $1  , $2, $3 , $4, now(), now());"

exports.searchAccountTable   = "SELECT * FROM pg_tables WHERE tablename = 'account'"
